name: flutter_sound_platform_interface
version: 7.8.0
description: The Dart interface to Flutter Sound.
#author: dooboolab<dooboolab@gmail.com>
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
homepage: https://github.com/Canardoux/tau
environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.8.0
